### ISSUE TITLE
Question About Datafiles

### ISSUE THREAD

**Issue by deku-0621** [ZhaohanM/FusionDTI#4]
Hello, author. Could you provide the data files that can be replicated? The UniProt IDs are difficult to obtain. Thanks!

**Comment by ZhaohanM** [comment]
Thank you for your interest in our work.

The step of obtaining the UniProt IDs is not mandatory, you can use amino acid sequences directly to obtain the corresponding protein structure files via [AlphaFold ](https://github.com/google-deepmind/alphafold) model. The datasets we have processed are not publicly available as further work is in progress. Thanks for your patience.

**Comment by deku-0621** [comment]
Thanks！
